version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    container_name: mariadb
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=bitnami
  wordpress:
    image: 'docker.io/bitnami/wordpress:5-debian-10'
    container_name: wordpress
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
    container_name: phpmyadmin
    ports:
      - '8081:8080'
      - '8444:8443'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
